export default {
  broker_hard_disk_usage: {
    global_topics_size: [
      {
        aliasColors: {},
        bars: false,
        dashLength: 10,
        dashes: false,
        datasource: 'Prometheus',
        fill: 1,
        gridPos: {
          h: 9,
          w: 12,
          x: 0,
          y: 0,
        },
        id: 2,
        legend: {
          alignAsTable: true,
          avg: false,
          current: true,
          max: false,
          min: false,
          rightSide: true,
          show: true,
          sort: 'current',
          sortDesc: true,
          total: false,
          values: true,
        },
        lines: true,
        linewidth: 1,
        links: [],
        nullPointMode: 'null',
        percentage: false,
        pointradius: 5,
        points: false,
        renderer: 'flot',
        seriesOverrides: [],
        spaceLength: 10,
        stack: true,
        steppedLine: false,
        targets: [
          {
            expr: 'sum(kafka_log_size{env="$env"}) by (topic)',
            format: 'time_series',
            intervalFactor: 1,
            legendFormat: '{{topic}}',
            refId: 'A',
          },
        ],
        thresholds: [],
        timeFrom: null,
        timeShift: null,
        title: 'Global Topics Size (including replicas)',
        tooltip: {
          shared: true,
          sort: 1,
          value_type: 'individual',
        },
        type: 'graph',
        xaxis: {
          buckets: null,
          mode: 'time',
          name: null,
          show: true,
          values: [],
        },
        yaxes: [
          {
            format: 'decbytes',
            label: null,
            logBase: 1,
            max: null,
            min: null,
            show: true,
          },
          {
            format: 'short',
            label: null,
            logBase: 1,
            max: null,
            min: null,
            show: true,
          },
        ],
        yaxis: {
          align: false,
          alignLevel: null,
        },
      },
      {
        aliasColors: {},
        bars: false,
        dashLength: 10,
        dashes: false,
        datasource: 'Prometheus',
        fill: 1,
        gridPos: {
          h: 9,
          w: 12,
          x: 12,
          y: 0,
        },
        id: 5,
        legend: {
          alignAsTable: true,
          avg: false,
          current: true,
          max: false,
          min: false,
          rightSide: true,
          show: true,
          total: false,
          values: true,
        },
        lines: true,
        linewidth: 1,
        links: [],
        nullPointMode: 'null',
        percentage: false,
        pointradius: 5,
        points: false,
        renderer: 'flot',
        seriesOverrides: [],
        spaceLength: 10,
        stack: false,
        steppedLine: false,
        targets: [
          {
            expr: 'sum(sum(kafka_log_size{env="$env"}) by (topic, partition) / sum(kafka_cluster_partition_replicascount{env="$env"}) by(partition, topic)) by (topic)',
            format: 'time_series',
            intervalFactor: 1,
            legendFormat: '{{topic}}',
            refId: 'A',
          },
        ],
        thresholds: [],
        timeFrom: null,
        timeShift: null,
        title: 'Global Topics Size (without replication)',
        tooltip: {
          shared: true,
          sort: 0,
          value_type: 'individual',
        },
        type: 'graph',
        xaxis: {
          buckets: null,
          mode: 'time',
          name: null,
          show: true,
          values: [],
        },
        yaxes: [
          {
            format: 'decbytes',
            label: null,
            logBase: 1,
            max: null,
            min: null,
            show: true,
          },
          {
            format: 'short',
            label: null,
            logBase: 1,
            max: null,
            min: null,
            show: true,
          },
        ],
        yaxis: {
          align: false,
          alignLevel: null,
        },
      },
    ],
    log_size_per_broker: [
      {
        aliasColors: {},
        bars: false,
        dashLength: 10,
        dashes: false,
        datasource: 'Prometheus',
        fill: 1,
        gridPos: {
          h: 7,
          w: 12,
          x: 0,
          y: 9,
        },
        id: 3,
        legend: {
          alignAsTable: false,
          avg: false,
          current: false,
          max: false,
          min: false,
          rightSide: false,
          show: true,
          total: false,
          values: false,
        },
        lines: true,
        linewidth: 1,
        links: [],
        nullPointMode: 'null',
        percentage: false,
        pointradius: 5,
        points: false,
        renderer: 'flot',
        seriesOverrides: [],
        spaceLength: 10,
        stack: true,
        steppedLine: false,
        targets: [
          {
            expr: 'sum(kafka_log_size{env="$env"}) by (instance)',
            format: 'time_series',
            intervalFactor: 1,
            legendFormat: '{{instance}}',
            refId: 'A',
          },
        ],
        thresholds: [],
        timeFrom: null,
        timeShift: null,
        title: 'Log Size Per Broker (including replicas)',
        tooltip: {
          shared: true,
          sort: 1,
          value_type: 'individual',
        },
        type: 'graph',
        xaxis: {
          buckets: null,
          mode: 'time',
          name: null,
          show: true,
          values: [],
        },
        yaxes: [
          {
            format: 'decbytes',
            label: null,
            logBase: 1,
            max: null,
            min: null,
            show: true,
          },
          {
            format: 'short',
            label: null,
            logBase: 1,
            max: null,
            min: null,
            show: true,
          },
        ],
        yaxis: {
          align: false,
          alignLevel: null,
        },
      },
    ],
  },
};
