{
 "title": "Kafka Broker / Zookeeper Connection",
 "tags": [
  "kafka",
  "zookeeper"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "label_values(kafka_server_brokerstate, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka/Zookeeper Session Expire Listener",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Zookeeper Sync Connects Per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeepersyncconnectspersec{aggregate=\"OneMinute\", env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Zookeeper Disconnects Per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeeperdisconnectspersec{env=\"$env\", aggregate=\"OneMinute\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Zookeeper Read Only Connects Per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeeperreadonlyconnectspersec{env=\"$env\", aggregate=\"OneMinute\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Zookeeper Expires Per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeeperexpirespersec{env=\"$env\", aggregate=\"OneMinute\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Zookeeper SASL Authentications Per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeeperauthfailurespersec{env=\"$env\", aggregate=\"OneMinute\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Zookeeper Auth Failures Per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeeperauthfailurespersec{env=\"$env\", aggregate=\"OneMinute\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}