{
 "title": "Kafka / Hard Disk Usage",
 "tags": [
  "kafka",
  "topics",
  "disk"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "label_values(kafka_log_size, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "Global Topics Size (including replicas)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_size{env=\"$env\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Global Topics Size (without replication)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(kafka_log_size{env=\"$env\"}) by (topic, partition) / sum(kafka_cluster_partition_replicascount{env=\"$env\"}) by(partition, topic)) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Log Size Per Broker (including replicas)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_size{env=\"$env\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}